%----------------------------
% FIT OPTIONS UITABLES
%----------------------------
handles.fit1optionsuitable = olduitable(panel_Fit,...
    'Tag','fit1optionsuitable',...
    'ColumnFormat',{'numeric' 'numeric' 'numeric' 'numeric' 'numeric' 'numeric'},...
    'Data',FitInput,...
    'Units','normalized', ...
    'Position',[0.01 .25 .99 .745],...
    'Visible', 'on',...
    'ColumnEditable',true,...
    'ColumnName',{'K' '<html><center />&alpha<br /> [Gy<sup>-1</sup>]</html>' ...
    '<html><center />&beta<br />[Gy<sup>-2</sup>]</html>' '<html>&gamma</html>' ...
    '<html><center />a <br />[mo<sup>-1</sup>]</html>' '<html>&delta</html>'},...
    'ColumnWidth',100,...
    'RowName',{'Initial Guess' 'Lower limit' 'Upper limit'},...
    'Userdata',FitInput,...
    'CellEditCallback',@fitoptionsuitable_Callback);